In [22]:
import torch

In [23]:
x = torch.ones(2, 2, requires_grad=True) # requires_grad : 나중에 미분을 사용할 것인가?

In [24]:
y = x + 1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [25]:
z = 2 * y ** 2
print(z)
res = z.mean()
print(res)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
tensor(8., grad_fn=<MeanBackward0>)


In [26]:
# d(res) / dx_i
res.backward()

In [27]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])
